"""camera zone column

Revision ID: 86a62d7f55fc
Revises: 050111a6ca5b
Create Date: 2026-07-09 10:25:05.970555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a62d7f55fc'
down_revision: Union[str, Sequence[str], None] = '050111a6ca5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('zone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'zone')
    # ### end Alembic commands ###
